### PR TITLE
#5

### PR DESCRIPTION
**Pull request by GeorgeWinner9E**
#5 создаю pull request не своих репозиториев 
#6

### CODE REVIEW

**Comment by GeorgeWinner9E** [comment]
Мне нравится

**Comment by maximrufed** [comment]
TOP Request!!! That's really great!

**Comment by maximrufed** [comment]
Doloy konflikty!

**Comment by LaidProgrammer** [comment]
Your request has conflicts

**Comment by maximrufed** [comment]
Doloy kalaboratorov!

**Comment by maximrufed** [comment]
Bynd!

**Comment by maximrufed** [comment]
Resistance would never die!

**Pull request merged**
